###

POST http://localhost:8080/predict
Content-Type: application/json

{
    "article" : "সর্বশেষ ২৪ ঘণ্টায় ৮ জনের করোনা শনাক্ত হয়েছে। এ সময় করোনায় কারও মৃত্যু হয়নি। গতকাল করোনায় একজনের মৃত্যু হয়েছে। এ সময় ১১ জনের করোনা শনাক্ত হয়েছে।আজ স্বাস্থ্য অধিদপ্তরের দেওয়া বিজ্ঞপ্তিতে এ তথ্য তুলে ধরা হয়েছে। এতে বলা হয়েছে, সর্বশেষ ২৪ ঘণ্টায় সারা দেশে ২ হাজার ২০৫ জনের নমুনা পরীক্ষা করা হয়। পরীক্ষার বিপরীতে করোনা শনাক্তের হার শূন্য দশমিক ৩৬। গতকাল শনাক্তের হার ছিল শূন্য দশমিক ৪২।" 
}