###
POST http://localhost:3333/api/post-article
Content-Type: application/json

{
    "article" : "Hello"
}

###
POST http://localhost:3333/api/trained_article
Content-Type: application/json

{
    "article" : "২০২১–২২ মৌসুমে এসি মিলানকে শিরোপা জেতাতে বড় ভূমিকা রেখেছিলেন জ্লাতান ইব্রাহিমোভিচ। কিন্তু শিরোপা জয়ের পরপরই মাঠের বাইরে ছিটকে যান সুইডিশ তারকা। হাঁটুর চোট সারাতে করতে হয়েছিল অস্ত্রোপচার। প্রায় ৯ মাস মাঠের বাইরে থাকার পর চোট থেকে সেরে উঠে ফেরার জন্য তৈরি হচ্ছেন ইব্রা। ফেরার আগে স্বভাবসুলভ ভঙ্গিতে একটা হুঙ্কারও দিয়েছেন বার্সেলোনা ও ইন্টার মিলানের সাবেক ফরোয়ার্ড।বয়স হয়ে গেছে ৪১ বছর। এ বয়সে অনেক ফুটবলারই অবসরে চলে যান। যাঁরা এই বয়সেও খেলছেন, তাঁরা হয়তো অবসরে যাওয়ার কথা ভাবছেন। কিন্তু ইব্রাহিমোভিচ এই দলে নন। অনেকেই ভাবছিলেন, হাঁটুর চোট হয়তো ইব্রার ক্যারিয়ার শেষ করে দেবে। কিন্তু, এসি মিলানের ফরোয়ার্ড ইব্রাহিমোভিচ ঘোষণা দিয়েছেন, তিনি আরও ভালো কিছু করার জন্য উন্মুখ হয়ে আছেন।এখানেই থেমে থাকেননি ইব্রা। এই ৪১ বছর বয়সেও নিজেকে অনেক উঁচুতে রাখছেন সুইডিশ ফরোয়ার্ড, ‘আমি এখনো ঈশ্বর, আমি এখনো এক নম্বর। আমি যখন ফিরব, সবকিছু বদলে যাবে। সত্যি আমি অনেক কিছু করতে চাই। এই কয় মাসে আমি অনেক কিছু হারিয়েছি, সময় নষ্ট করেছি।’",
    "category" : "sports",
    "Source_link" : "https://www.prothomalo.com/opinion/column/34m01khyxf",
    "Source" : "Prothom Alo",
    "Writer" : "জেফ পাও"
}